spring:
  config:
    activate:
      on-profile : local
  application:
    name: everyone
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:member;MODE=MySQL
    username: sa
    password: ''
  #        hikari:
  #            connectionTimeout: 30000.0
  #            idleTimeout: 600000.0
  #            maxLifetime: 1800000.0
  #            driver-class-name: org.h2.Driver
  #            jdbc-url: jdbc:h2:mem:member
  #            username: sa
  #            password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true         # 쿼리 로그 포맷 (정렬)
        #                show_sql: true           # 쿼리 로그 출력
        use_sql_comments: true
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8080
  servlet:
    context-path: /api
logging.level:
  org.hibernate.SQL: debug            # 로그 파일로 Sql을 출력

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework: info


---
spring:
  config:
    activate:
      on-profile : dev
  application:
    name: everyone
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:member;MODE=MySQL
      username: sa
      password: ''
    #        hikari:
    #            connectionTimeout: 30000.0
    #            idleTimeout: 600000.0
    #            maxLifetime: 1800000.0
    #            driver-class-name: org.h2.Driver
    #            jdbc-url: jdbc:h2:mem:member
    #            username: sa
    #            password: ''
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true         # 쿼리 로그 포맷 (정렬)
          #                show_sql: true           # 쿼리 로그 출력
          use_sql_comments: true
    output:
      ansi:
        enabled: ALWAYS
  server:
    port: 8080
    servlet:
      context-path: /api
  logging.level:
    org.hibernate.SQL: debug            # 로그 파일로 Sql을 출력

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
        springframework: info